# time for display-message "..."
set-option -g display-time 1500

# *-style are for tmux 2.9+ only
# set-option -g message-style fg='#312d2a',bg='#e5dbbe'
# set-window-option -g window-status-current-style fg='#312d2a' # orange

# windows numbering starts at 1
# set -g base-index 1

# don't change the window name
set-option -g allow-rename off

# allow mouse control (requires tmux > 2.1)
set -g mouse on

# use vi mode
set-window-option -g mode-keys vi

# bind c-B n to search previous SQL>
bind-key n copy-mode \; send-keys "k?SQL> " c-M

# history my use too much memory?
set -g history-limit 100000

# control B + Shift P stores the screen history
bind-key P command-prompt -p 'save history to filename:' -I '~/tmux-history-%Y%m%d%H%M%S' 'capture-pane -S -32768 ; save-buffer %1.txt ; delete-buffer ; clear-history'

# The colors I like
set -g display-panes-active-colour '#2c5967' # blueish
set -g display-panes-colour '#2b6242'  # light indigo?
set -g status-bg '#e5dbbe'
set -g status-fg '#312d2a' # light indigo
set -g status-keys vi
set -g status-left "your status here [#S]"
set -g status-left-length 20
set -g status-justify centre

set -g pane-border-style "fg=#94afaf"
set -g pane-active-border-style "bg=default fg=#facd62"
